//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimulationTests.data", typeof(data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Copenhagen&quot;,
        ///  &quot;vertices&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;DTU&quot;,
        ///      &quot;type&quot;: &quot;base&quot;,
        ///      &quot;latitude&quot;: 55.786327,
        ///      &quot;longitude&quot;: 12.523387,
        ///      &quot;edges&quot;: [
        ///        &quot;Tivoli&quot;,
        ///        &quot;Amager Strandpark&quot;,
        ///        &quot;Ballerup&quot;
        ///      ]
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Glostrup&quot;,
        ///      &quot;type&quot;: &quot;base&quot;,
        ///      &quot;latitude&quot;: 55.663069,
        ///      &quot;longitude&quot;: 12.397718,
        ///      &quot;edges&quot;: [
        ///        &quot;Tivoli&quot;,
        ///        &quot;Roskilde&quot;,
        ///        &quot;Ballerup&quot;,
        ///        &quot;Brondby Strand&quot;
        ///      ]
        ///    },
        ///    {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string copenhagen {
            get {
                return ResourceManager.GetString("copenhagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Drone&quot;,
        ///    &quot;speed&quot;: 30,
        ///    &quot;maxRange&quot;: 80,
        ///    &quot;movementPenalty&quot;: 1.0,
        ///    &quot;maxPayload&quot;: 5,
        ///    &quot;costPerHour&quot;: 10,
        ///    &quot;costPerKm&quot;: 5
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Truck&quot;,
        ///    &quot;speed&quot;: 80,
        ///    &quot;maxRange&quot;: 500,
        ///    &quot;movementPenalty&quot;: 1.5,
        ///    &quot;maxPayload&quot;: 30000,
        ///    &quot;costPerHour&quot;: 50,
        ///    &quot;costPerKm&quot;: 2
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Ship&quot;,
        ///    &quot;speed&quot;: 10,
        ///    &quot;maxRange&quot;: 2000,
        ///    &quot;movementPenalty&quot;: 1.0,
        ///    &quot;maxPayload&quot;: 80000,
        ///    &quot;costPerHour&quot;: 35,
        ///    &quot;costPerKm&quot;: 0.5
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vehicles {
            get {
                return ResourceManager.GetString("vehicles", resourceCulture);
            }
        }
    }
}
