---

name: unittests
# Run workflow on every push to the master branch
on: [push, pull_request]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v2
        
      # sets up .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: 5.0.100
          
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish Caelicus/Caelicus.csproj -c Release -o release --nologo
        
      # Unit Tests    
      - name: UnitTests 
        run: dotnet test SimulationTests/SimulationTests.csproj
